kind: Deployment
apiVersion: apps/v1
metadata:
  name: dip-policy-storage
  labels:
    app: dip-policy-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dip-policy-storage
  template:
    metadata:
      labels:
        app: dip-policy-storage
    spec:
      containers:
        - name: dip-policy-storage
          image: <!--image-->
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: MESSAGE_BROKER
              value: "amqp://platform:guest@$(RABBITMQ_SERVICE_HOST):$(RABBITMQ_SERVICE_PORT_AMQP)/trusted"
          envFrom:
            - secretRef:
                name: pg-connection
          livenessProbe:
            httpGet:
              path: /live
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1
            successThreshold: 1
