apiVersion: v1
kind: Secret
metadata:
  name: pg-connection
type: Opaque
data:
  # postgresql://dipadmin:dippassword@postgres:5432/dip
  POSTGRES_DB: ZGlw
  POSTGRES_USER: ZGlwYWRtaW4=
  POSTGRES_PASSWORD: ZGlwcGFzc3dvcmQ=
  SALT: c2FsdA==
