apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
data:
  AMQP_PLATFORM_USERNAME: cGxhdGZvcm0=
  AMQP_PLATFORM_PASSWORD: Z3Vlc3Q=
  AMQP_ADMIN_USERNAME: YWRtaW4=
  AMQP_ADMIN_PASSWORD: Z3Vlc3Q=
