apiVersion: v1
kind: Secret
metadata:
  name: payment
type: Opaque
data:
  STRIPE_PUBLIC_KEY: cGtfdGVzdF9HOUNTVFpUbkFTZFpIeUFsQUdsc3RTNmM=
  STRIPE_SECRET_KEY: c2tfdGVzdF81NVZ4Q0JIOHlnZFRVR2J0YTBqQWlJSms=
